In [2]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
import pandas as pd
import tensorflow as tf
 
# Read Input Data
data = pd.read_csv("팀투수_통합.csv")


# 이름만 바꿈
OB = data[data['T_ID']=='OB']
HH = data[data['T_ID']=='HH']
data = data[data['T_ID']=='HT']
KT = data[data['T_ID']=='KT']
LG = data[data['T_ID']=='LG']
LT = data[data['T_ID']=='LT']
NC = data[data['T_ID']=='NC']
SK = data[data['T_ID']=='SK']
SS = data[data['T_ID']=='SS']
WO = data[data['T_ID']=='WO']

# data = data[(data['WLS']!='D')]

print(len(data))
data.info()

Using TensorFlow backend.
C:\Anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

350
<class 'pandas.core.frame.DataFrame'>
Int64Index: 350 entries, 2 to 3516
Data columns (total 34 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   G_ID        350 non-null    object
 1   GDAY_DS     350 non-null    int64
 2   T_ID        350 non-null    object
 3   VS_T_ID     350 non-null    object
 4   HEADER_NO   350 non-null    int64
 5   TB_SC       350 non-null    object
 6   CG_CK       350 non-null    int64
 7   WLS         350 non-null    object
 8   HOLD        350 non-null    int64
 9   INN2        350 non-null    int64
 10  BF          350 non-null    int64
 11  PA          350 non-null    int64
 12  AB          350 non-null    int64
 13  HIT         350 non-null    int64
 14  H2          350 non-null    int64
 15  H3          350 non-null    int64
 16  HR          350 non-null    int64
 17  SB          350 non-null    int64
 18  CS          350 non-null    int64
 19  SH          350 non-null    int64
 20  SF          350 non-null    int64
 21  BB          350 non-null    int64
 22  IB          350 non-null    int64
 23  HP          350 non-null    int64
 24  KK          350 non-null    int64
 25  GD          350 non-null    int64
 26  WP          350 non-null    int64
 27  BK          350 non-null    int64
 28  ERR         350 non-null    int64
 29  R           350 non-null    int64
 30  ER          350 non-null    int64
 31  P_WHIP_RT   350 non-null    float64
 32  P2_WHIP_RT  350 non-null    float64
 33  CB_WHIP_RT  350 non-null    float64
dtypes: float64(3), int64(26), object(5)
memory usage: 95.7+ KB

In [3]:
data.head(14)

,G_ID,GDAY_DS,T_ID,VS_T_ID,HEADER_NO,TB_SC,CG_CK,WLS,HOLD,INN2,...,KK,GD,WP,BK,ERR,R,ER,P_WHIP_RT,P2_WHIP_RT,CB_WHIP_RT
2,20180324KTHT0,20180324,HT,KT,0,B,0,L,0,27,...,9,0,0,0,0,5,5,2.000000,1.333333,1.500000
12,20180325KTHT0,20180325,HT,KT,0,B,0,W,0,27,...,8,1,0,0,0,1,1,0.000000,1.000000,1.500000
28,20180327SSHT0,20180327,HT,SS,0,B,0,W,0,27,...,5,1,1,0,0,0,0,0.428571,0.500000,1.500000
38,20180328SSHT0,20180328,HT,SS,0,B,0,L,0,27,...,7,2,0,0,0,6,6,1.666667,1.500000,1.250000
48,20180329SSHT0,20180329,HT,SS,0,B,0,W,0,27,...,9,1,0,0,0,0,0,1.000000,1.400000,0.900000
51,20180330HTLG0,20180330,HT,LG,0,T,0,W,3,27,...,6,1,0,0,0,3,3,0.900000,1.250000,5.400000
61,20180331HTLG0,20180331,HT,LG,0,T,0,L,0,24,...,5,0,1,0,0,6,6,1.200000,1.363636,1.500000
71,20180401HTLG0,20180401,HT,LG,0,T,0,L,0,26,...,3,0,0,0,0,6,6,2.400000,1.730769,3.000000
81,20180403HTSK0,20180403,HT,SK,0,T,0,L,0,24,...,7,0,1,0,0,13,13,2.500000,18.000000,2.250000
91,20180404HTSK0,20180404,HT,SK,0,T,0,W,0,30,...,11,1,2,0,0,6,6,3.000000,1.500000,1.200000
106,20180406WOHT0,20180406,HT,WO,0,B,0,W,0,27,...,13,0,1,0,0,5,5,1.714286,1.666667,0.900000
116,20180407WOHT0,20180407,HT,WO,0,B,0,W,0,27,...,6,1,0,0,0,1,1,2.250000,1.000000,1.333333
126,20180408WOHT0,20180408,HT,WO,0,B,0,W,1,27,...,6,0,1,0,0,3,3,0.461538,1.666667,2.625000
129,20180410HTHH0,20180410,HT,HH,0,T,0,L,0,24,...,8,0,0,0,0,4,4,0.000000,1.375000,4.200000

In [6]:
# (승,패,무) 숫자로 바꿔주기
data.WLS = data.WLS.replace('W',1)
data.WLS = data.WLS.replace('L',-1)
data.WLS = data.WLS.replace('D',0)
data.WLS = data.WLS.astype(int)
# 
x_data = np.array(data.iloc[:-30,[9,11,10,12,13,16,21,24,29,30]])
y_data = np.array(data.iloc[30:,7:8])
xx_data = np.array(data.iloc[-20:,[9,11,10,12,13,16,21,24,29,30]])



print(x_data.shape)
print(y_data.shape)

(320, 10)
(320, 1)

In [98]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_data,y_data,random_state=66,test_size = 0.3)

In [99]:
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=3, n_estimators=10, max_depth=4)

model

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=5, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=3, verbose=0,
                       warm_start=False)

In [100]:
# 모델 훈련
model.fit(x_train,y_train)
print("훈련 세트 정확도: {:.3f}".format(model.score(x_train, y_train)))
print("테스트 세트 정확도: {:.3f}".format(model.score(x_test, y_test)))

훈련 세트 정확도: 0.790
테스트 세트 정확도: 0.500

C:\Anaconda3\envs\venv\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

In [132]:
# 예측 된 값 보기
prediction = model.predict(xx_data)

prediction

array([-1, -1,  1,  1, -1, -1,  1, -1, -1, -1,  1, -1, -1, -1, -1,  1, -1,
       -1, -1, -1])

In [104]:
# 승패예측 저장(1)
import csv
f = open('잔여경기.csv','r')
rdr = csv.reader(f)
lines = []
num=0
for line in rdr:
    if line[0] == "KIA":
        line[2] = prediction[num]
        num = num+1
    lines.append(line)
f.close()

f = open('잔여경기.csv','w',newline='') #원본을 훼손할 위험이 있으니 다른 파일에 저장하는 것을 추천합니다.
wr = csv.writer(f)
wr.writerows(lines)

f.close()

print

In [189]:
#무승부 데이터로 인해 승률예측이 잘 안돼서 무승부를 처리하기 위한 부분
f = open('잔여경기.csv','r')
rdr = csv.reader(f)
lines = []
for i in rdr:
    lines.append(i)
lines 
del lines[0]
print(len(lines))
lines

186

[['롯데', 'LG', '1', '', ''],
 ['LG', '롯데', '-1', '', ''],
 ['KT', '삼성', '1', '', ''],
 ['삼성', 'KT', '-1', '', ''],
 ['SK', 'NC', '1', '', ''],
 ['NC', 'SK', '1', '', ''],
 ['KIA', '키움', '-1', '', ''],
 ['키움', 'KIA', '-1', '', ''],
 ['두산', '한화', '1', '', ''],
 ['한화', '두산', '-1', '', ''],
 ['롯데', 'LG', '-1', '', ''],
 ['LG', '롯데', '-1', '', ''],
 ['KT', '삼성', '-1', '', ''],
 ['삼성', 'KT', '-1', '', ''],
 ['SK', 'NC', '-1', '', ''],
 ['NC', 'SK', '-1', '', ''],
 ['KIA', '키움', '-1', '', ''],
 ['키움', 'KIA', '-1', '', ''],
 ['두산', '한화', '1', '', ''],
 ['한화', '두산', '-1', '', ''],
 ['롯데', 'LG', '-1', '', ''],
 ['LG', '롯데', '1', '', ''],
 ['KT', '삼성', '-1', '', ''],
 ['삼성', 'KT', '-1', '', ''],
 ['SK', 'NC', '1', '', ''],
 ['NC', 'SK', '1', '', ''],
 ['KIA', '키움', '1', '', ''],
 ['키움', 'KIA', '-1', '', ''],
 ['두산', '한화', '1', '', ''],
 ['한화', '두산', '1', '', ''],
 ['KIA', '두산', '1', '', ''],
 ['두산', 'KIA', '1', '', ''],
 ['키움', 'SK', '-1', '', ''],
 ['SK', '키움', '-1', '', ''],
 ['한화', '롯데', '-1', '', ''],
 ['롯데', '한화', '1', '', ''],
 ['삼성', 'NC', '-1', '', ''],
 ['NC', '삼성', '-1', '', ''],
 ['LG', 'KT', '-1', '', ''],
 ['KT', 'LG', '-1', '', ''],
 ['KIA', '두산', '-1', '', ''],
 ['두산', 'KIA', '1', '', ''],
 ['키움', 'SK', '-1', '', ''],
 ['SK', '키움', '1', '', ''],
 ['한화', '롯데', '-1', '', ''],
 ['롯데', '한화', '1', '', ''],
 ['삼성', 'NC', '-1', '', ''],
 ['NC', '삼성', '1', '', ''],
 ['LG', 'KT', '1', '', ''],
 ['KT', 'LG', '-1', '', ''],
 ['KIA', '두산', '-1', '', ''],
 ['두산', 'KIA', '1', '', ''],
 ['키움', 'SK', '-1', '', ''],
 ['SK', '키움', '1', '', ''],
 ['한화', '롯데', '-1', '', ''],
 ['롯데', '한화', '-1', '', ''],
 ['삼성', 'NC', '1', '', ''],
 ['NC', '삼성', '1', '', ''],
 ['LG', 'KT', '1', '', ''],
 ['KT', 'LG', '1', '', ''],
 ['삼성', 'LG', '1', '', ''],
 ['LG', '삼성', '1', '', ''],
 ['두산', 'SK', '1', '', ''],
 ['SK', '두산', '1', '', ''],
 ['KT', '롯데', '-1', '', ''],
 ['롯데', 'KT', '1', '', ''],
 ['한화', 'KIA', '1', '', ''],
 ['KIA', '한화', '1', '', ''],
 ['NC', '키움', '1', '', ''],
 ['키움', 'NC', '1', '', ''],
 ['삼성', 'LG', '-1', '', ''],
 ['LG', '삼성', '1', '', ''],
 ['두산', 'SK', '1', '', ''],
 ['SK', '두산', '1', '', ''],
 ['KT', '롯데', '-1', '', ''],
 ['롯데', 'KT', '-1', '', ''],
 ['NC', '키움', '-1', '', ''],
 ['키움', 'NC', '1', '', ''],
 ['한화', 'KIA', '-1', '', ''],
 ['KIA', '한화', '-1', '', ''],
 ['삼성', 'LG', '-1', '', ''],
 ['LG', '삼성', '1', '', ''],
 ['두산', 'SK', '1', '', ''],
 ['SK', '두산', '-1', '', ''],
 ['KT', '롯데', '-1', '', ''],
 ['롯데', 'KT', '1', '', ''],
 ['한화', 'KIA', '-1', '', ''],
 ['KIA', '한화', '-1', '', ''],
 ['NC', '키움', '1', '', ''],
 ['키움', 'NC', '1', '', ''],
 ['NC', 'LG', '1', '', ''],
 ['LG', 'NC', '1', '', ''],
 ['롯데', '삼성', '1', '', ''],
 ['삼성', '롯데', '-1', '', ''],
 ['두산', 'KT', '1', '', ''],
 ['KT', '두산', '-1', '', ''],
 ['SK', 'KIA', '1', '', ''],
 ['KIA', 'SK', '-1', '', ''],
 ['키움', '한화', '1', '', ''],
 ['한화', '키움', '-1', '', ''],
 ['롯데', '삼성', '-1', '', ''],
 ['삼성', '롯데', '-1', '', ''],
 ['두산', 'KT', '1', '', ''],
 ['KT', '두산', '-1', '', ''],
 ['SK', 'KIA', '1', '', ''],
 ['KIA', 'SK', '1', '', ''],
 ['키움', '한화', '-1', '', ''],
 ['한화', '키움', '-1', '', ''],
 ['NC', 'LG', '1', '', ''],
 ['LG', 'NC', '1', '', ''],
 ['NC', 'LG', '-1', '', ''],
 ['LG', 'NC', '1', '', ''],
 ['롯데', '삼성', '-1', '', ''],
 ['삼성', '롯데', '-1', '', ''],
 ['두산', 'KT', '1', '', ''],
 ['KT', '두산', '1', '', ''],
 ['SK', 'KIA', '1', '', ''],
 ['KIA', 'SK', '-1', '', ''],
 ['키움', '한화', '1', '', ''],
 ['한화', '키움', '-1', '', ''],
 ['한화', '두산', '-1', '', ''],
 ['두산', '한화', '1', '', ''],
 ['LG', '롯데', '-1', '', ''],
 ['롯데', 'LG', '1', '', ''],
 ['SK', '삼성', '1', '', ''],
 ['삼성', 'SK', '-1', '', ''],
 ['KIA', 'NC', '-1', '', ''],
 ['NC', 'KIA', '-1', '', ''],
 ['키움', 'KT', '1', '', ''],
 ['KT', '키움', '-1', '', ''],
 ['한화', '두산', '-1', '', ''],
 ['두산', '한화', '-1', '', ''],
 ['LG', '롯데', '-1', '', ''],
 ['롯데', 'LG', '-1', '', ''],
 ['SK', '삼성', '1', '', ''],
 ['삼성', 'SK', '-1', '', ''],
 ['KIA', 'NC', '-1', '', ''],
 ['NC', 'KIA', '-1', '', ''],
 ['키움', 'KT', '1', '', ''],
 ['KT', '키움', '-1', '', ''],
 ['한화', '두산', '-1', '', ''],
 ['두산', '한화', '1', '', ''],
 ['LG', '롯데', '-1', '', ''],
 ['롯데', 'LG', '-1', '', ''],
 ['SK', '삼성', '1', '', ''],
 ['삼성', 'SK', '-1', '', ''],
 ['KIA', 'NC', '-1', '', ''],
 ['NC', 'KIA', '1', '', ''],
 ['키움', 'KT', '1', '', ''],
 ['KT', '키움', '1', '', ''],
 ['KIA', 'LG', '1', '', ''],
 ['LG', 'KIA', '1', '', ''],
 ['KT', 'SK', '-1', '', ''],
 ['SK', 'KT', '1', '', ''],
 ['롯데', 'NC', '-1', '', ''],
 ['NC', '롯데', '1', '', ''],
 ['두산', '키움', '1', '', ''],
 ['키움', '두산', '1', '', ''],
 ['삼성', '한화', '-1', '', ''],
 ['한화', '삼성', '-1', '', ''],
 ['KIA', 'LG', '-1', '', ''],
 ['LG', 'KIA', '1', '', ''],
 ['KT', 'SK', '1', '', ''],
 ['SK', 'KT', '1', '', ''],
 ['롯데', 'NC', '-1', '', ''],
 ['NC', '롯데', '1', '', ''],
 ['두산', '키움', '1', '', ''],
 ['키움', '두산', '1', '', ''],
 ['삼성', '한화', '-1', '', ''],
 ['한화', '삼성', '-1', '', ''],
 ['KIA', 'LG', '-1', '', ''],
 ['LG', 'KIA', '1', '', ''],
 ['KT', 'SK', '-1', '', ''],
 ['SK', 'KT', '1', '', ''],
 ['롯데', 'NC', '-1', '', ''],
 ['NC', '롯데', '-1', '', ''],
 ['두산', '키움', '-1', '', ''],
 ['키움', '두산', '-1', '', ''],
 ['삼성', '한화', '1', '', ''],
 ['한화', '삼성', '-1', '', ''],
 ['KT', 'SK', '-1', '', ''],
 ['SK', 'KT', '1', '', ''],
 ['롯데', 'NC', '1', '', ''],
 ['NC', '롯데', '-1', '', ''],
 ['두산', '키움', '1', '', ''],
 ['키움', '두산', '-1', '', '']]

In [190]:
# 최근 경기 (승 무 패) - 무승부일때 최근전적으로 판별
a = [('NC', 9,0,1),('키움',5,0,5),('KT',7,0,3),('LG',5,0,5),('두산',3,0,7),('KIA',4,0,6),
('롯데',4,0,6),('삼성',3,0,7),('SK',3,0,7),('한화',7,0,3)]
# 팀 별 승률(승 패) 
win_rate = [['NC',0,0],['키움',0,0],['KT',0,0],['LG',0,0],['두산',0,0],['KIA',0,0],['롯데',0,0],['삼성',0,0],['SK',0,0],['한화',0,0]]

In [191]:
# 무승부일때 최근전적 10개로 승패 판별
for i in range(0,93):
    if lines[i*2][2] == lines[i*2+1][2]:
        name = lines[i*2][0]
        name2 = lines[i*2+1][0]
        one=0
        two=0
        for j in a:
            if j[0] == name:
                one = int(j[1])-int(j[3])
            elif j[0] ==name2:
                two = int(j[1])-int(j[3])
        if one>two:
            lines[i*2][2]='1'
            lines[i*2+1][2]='-1'
        elif one<two:
            lines[i*2][2]='-1'
            lines[i*2+1][2]='1'
        else:
            lines[i*2][2]= '0'
            lines[i*2+1][2]='0'
            
            
# 승률을 계산함
for i in lines:
    for j in win_rate:
        if j[0] == i[0]:
            if i[2] =='1':
                j[1] = j[1]+1
            elif i[2] =='-1':
                j[2] = j[2]+1
            else :
                pass
            if i[1]=='0':
                rate = 0
            elif i[2]=='0':
                rate = 1
            else :
                rate = j[1]/(j[1]+j[2])
            i[3] = rate
                
print(win_rate)

[['NC', 16, 3], ['키움', 11, 8], ['KT', 9, 10], ['LG', 12, 6], ['두산', 10, 9], ['KIA', 3, 15], ['롯데', 10, 9], ['삼성', 1, 17], ['SK', 10, 9], ['한화', 9, 9]]

In [205]:
# 무승부 문제를 처리 한 잔여경기에 대한 예측결과를 저장
f = open('잔여경기10.csv','w') #원본을 훼손할 위험이 있으니 다른 파일에 저장하는 것을 추천합니다.
wr = csv.writer(f)
for i in lines:
    wr.writerow(i)   
f.close()